# Don't add newline before showing prompt
add_newline = false

# For some reason default char is to big in my terminal
# This looks prettier
# You must have Nerd Fonts installed
[character]
success_symbol= "[ï‘ ](green)"
error_symbol= "[ï€](red)"
vicmd_symbol = "[ï‘ ](bold blue)"

[directory]
# Show max 8 directories
truncation_length = 8
# Show full path in git repo
truncate_to_repo = false
# Show directory path in blue color
style = "bold blue"

[rust]
disabled = false

#
# Disable all modules that I don't need
# 
[aws]
disabled = true

[battery]
disabled = true

[conda]
disabled = true

[dotnet]
disabled = true

# Hide context since when using rootless docker it shows whole socket path
[docker_context]
format = "via ğŸ‹ "

[golang]
disabled = true

[java]
disabled = true

[package]
disabled = true

[python]
disabled = true

[ruby]
disabled = true

[terraform]
disabled = true
